# Generated by Django 4.1.4 on 2023-01-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madawa', '0003_remove_order_id_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=200)),
                ('inventory_type', models.CharField(max_length=200)),
                ('inventory_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_number',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('tablets', 'tablets'), ('oil', 'oil'), ('liquid', 'liquid')], max_length=200),
        ),
    ]
