# Generated by Django 4.1.4 on 2023-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madawa', '0005_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_level',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('Main Pharmacy', 'Main Pharmacy'), ('Sub Pharmacy', 'Sub Pharmacy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('Mg', 'Mg'), ('Ml', 'ml')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('tablets', 'tablets'), ('ointment', 'ointment'), ('liquid', 'liquid')], max_length=200),
        ),
    ]
