# Generated by Django 4.1.4 on 2023-01-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madawa', '0006_remove_inventory_inventory_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200)),
                ('contact_add', models.CharField(max_length=200)),
                ('cust_email', models.CharField(max_length=200)),
                ('cust_pass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200)),
                ('admin_add', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_pass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='purchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.medicines')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.CharField(max_length=200)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.medicines')),
                ('phar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.pharmacist')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.purchasing')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.customer')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.purchasing')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madawa.sales')),
            ],
        ),
    ]
