# Generated by Django 4.1.4 on 2023-01-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madawa', '0007_customer_medicines_pharmacist_purchasing_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasing',
            name='amount',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
