# Generated by Django 4.1.4 on 2023-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madawa', '0008_purchasing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='age',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='count',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicines',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
