# Generated by Django 4.1.4 on 2023-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madawa', '0009_customer_age_pharmacist_age_sales_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='count',
            field=models.TextField(max_length=200),
        ),
    ]
